#!/bin/bash -e

DIR=$(dirname $0)
DIR=$(cd $DIR/..; pwd)

PRESTO_VERSION="0.74"
PRESTO_JAR="presto-cli-${PRESTO_VERSION}-executable.jar"

if [ ! -f ${DIR}/bin/${PRESTO_JAR} ]; then
  echo "" 1>&2
  echo "Downloading the Presto CLI JAR ..." 1>&2
  curl -o ${DIR}/bin/${PRESTO_JAR} "http://central.maven.org/maven2/com/facebook/presto/presto-cli/${PRESTO_VERSION}/${PRESTO_JAR}"
  chmod 755 ${DIR}/bin/${PRESTO_JAR}
  echo "" 1>&2
fi

LOCAL_PORT="12911"
TUNNEL_HOST="query-gateway.dataeng.netflix.net"
TARGET_HOST="presto.master.dataeng.netflix.net"
TARGET_PORT="8080"

onExit() {
  pkill -f "${LOCAL_PORT}:${TARGET_HOST}"
}
trap onExit EXIT

echo "" 1>&2
echo "Starting SSH Tunnel to '${TUNNEL_HOST}'" 1>&2
echo "" 1>&2
ssh -f "${TUNNEL_HOST}" -L "${LOCAL_PORT}:${TARGET_HOST}:${TARGET_PORT}" -N

echo "Starting Presto CLI connection to '${TARGET_HOST}:${TARGET_PORT}'" 1>&2
echo "" 1>&2
${DIR}/bin/${PRESTO_JAR} --server http://localhost:${LOCAL_PORT} --catalog hive --debug "$@"

